USE [FxPrice]
GO

/****** Object:  Table [dbo].[CcyPrices]    Script Date: 11/13/2017 12:21:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CcyPrices](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CcyName] [varchar](100) NOT NULL,
	[Bid] [decimal](18, 8) NULL,
	[Ask] [decimal](18, 8) NULL,
	[TimeStamp] [datetime] NOT NULL,
 CONSTRAINT [PK_CcyPrices] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
